version: "3.8"

services:
  postgres:
    image: postgres:13
    env_file:
      - ./.env
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate deploy && npm run superuser && npm run start"

volumes:
  postgres_data:
